version: '3.7'
services:
  tendermint-init:
    image: tendermint/tendermint:v0.32.2
    command: init
    volumes:
        - /tmp:/tendermint
  tendermint:
    depends_on:
      - tendermint-init
    image: tendermint/tendermint:v0.32.2
    command: node
    volumes:
      - /tmp:/tendermint
    restart: always
    ports:
      - "26656:26656"
  simple-storage:
    build:
      context: ../.
      dockerfile: hs-abci-example/Dockerfile
    restart: always
    expose:
      - "26658"
