name:                hs-abci-example
version:             0.1.0.0
github:              "f-o-a-m/hs-abci/hs-abci-example"
license:             Apache
author:              Martin Allen
maintainer:          "martin@foam.space"
copyright:           "2019 Martin Allen"

extra-source-files:
- protos/**/*.proto

description:         Please see the README on GitHub at <https://github.com/f-o-a-m/hs-abci/hs-abci-example#readme>

default-extensions:
  - DeriveGeneric
  - NamedFieldPuns
  - RecordWildCards
  - RankNTypes
  - TypeFamilies
  - FlexibleContexts
  - DataKinds
  - TypeApplications
  - OverloadedStrings
  - PolyKinds
  - GeneralizedNewtypeDeriving
  - ScopedTypeVariables
  - TupleSections
  - LambdaCase
  - GADTs
  - TypeOperators
  - FlexibleInstances
  - MultiParamTypeClasses
  - DefaultSignatures
  - FunctionalDependencies
  - TypeFamilyDependencies
  - DeriveFunctor
  - StandaloneDeriving
  - ConstraintKinds


dependencies:
- async
- avl-auth
- base >= 4.7 && < 5
- binary
- bytestring
- containers
- conduit
- cryptonite
- data-default-class
- errors
- exceptions
- free
- hs-abci-extra
- hs-abci-server
- hs-abci-types
- hs-abci-extra
- http-types
- kan-extensions
- katip
- lens
- memory
- mtl
- polysemy
- polysemy-plugin
- proto-lens
- proto-lens-runtime
- servant
- stm
- string-conversions
- text
- uri-bytestring

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup

library:
  source-dirs:
  - src
  - app
  ghc-options:
  - -fplugin=Polysemy.Plugin
  - -Werror
  - -Wall
  exposed-modules:
  - Tendermint.SDK.Store
  - Tendermint.SDK.Codec
  - Tendermint.SDK.StoreQueries
  - Tendermint.SDK.Subscription
  - Tendermint.SDK.AuthTreeStore
  - Tendermint.SDK.Router.Types
  - Tendermint.SDK.Router.Class
  - Tendermint.SDK.Router
  - Tendermint.SDK.Module

  - SimpleStorage.App
  - SimpleStorage.Application
  - SimpleStorage.Handlers
  - SimpleStorage.Modules.SimpleStorage
  - SimpleStorage.Types
  - SimpleStorage.Logging

  generated-exposed-modules:
  - Proto.SimpleStorage.Messages
  - Proto.SimpleStorage.Messages_Fields

executables:
  simple-storage:
    source-dirs:
    - app
    main: Main.hs
    ghc-options:
    - -Werror
    - -Wall
    dependencies:
    - hs-abci-example

tests:
  hs-abci-example-e2e:
    main:                Spec.hs
    source-dirs:         e2e-test
    other-modules:
    - SimpleStorage.Test.E2ESpec
    - SimpleStorage.Test.HandlersSpec
    ghc-options:
    - -Werror
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - aeson
      - aeson-pretty
      - hs-abci-example
      - hs-abci-types
      - hs-tendermint-client
      - hspec
      - QuickCheck

  hs-abci-example-test:
    main:                Spec.hs
    source-dirs:         sdk-test
    other-modules:
    - Tendermint.SDK.Test.StoreExample
    - Tendermint.SDK.Test.StoreExampleSpec
    - Tendermint.SDK.Test.ModuleSpec

    ghc-options:
    - -Werror
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    dependencies:
      - generic-arbitrary
      - hs-abci-example
      - hs-abci-server
      - hspec
      - hspec-core
      - hspec-discover
      - binary
      - QuickCheck
      - quickcheck-instances
