name:                hs-abci-example
version:             0.1.0.0
github:              "f-o-a-m/hs-abci/hs-abci-example"
license:             Apache
author:              Martin Allen
maintainer:          "martin@foam.space"
copyright:           "2019 Martin Allen"

extra-source-files:
- protos/**/*.proto

description:         Please see the README on GitHub at <https://github.com/f-o-a-m/hs-abci/hs-abci-example#readme>

default-extensions:
  - DeriveGeneric
  - NamedFieldPuns
  - RecordWildCards
  - RankNTypes
  - TypeFamilies
  - FlexibleContexts
  - DataKinds
  - TypeApplications
  - OverloadedStrings
  - PolyKinds
  - GeneralizedNewtypeDeriving
  - ScopedTypeVariables
  - TupleSections
  - LambdaCase
  - GADTs
  - TypeOperators
  - FlexibleInstances
  - MultiParamTypeClasses
  - DefaultSignatures
  - FunctionalDependencies
  - TypeFamilyDependencies
  - DeriveFunctor


dependencies:
- base >= 4.7 && < 5
- binary
- bytestring
- containers
- cryptonite
- data-default-class
- hs-abci-server
- hs-abci-types
- hs-abci-extra
- http-types
- lens
- avl-auth
- memory
- mtl
- proto-lens
- proto-lens-runtime
- servant
- stm
- string-conversions
- text
- uri-bytestring

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup

library:
  source-dirs:
  - src
  - app
  ghc-options:
  - -Werror
  - -Wall
  exposed-modules:
  - Tendermint.SDK.DB
  - Tendermint.SDK.Transaction
  - Tendermint.SDK.StoreExample
  - Tendermint.SDK.Codec

  - SimpleStorage.App
  - SimpleStorage.Application
  - SimpleStorage.Handlers
  - SimpleStorage.StateMachine
  - SimpleStorage.Types

  generated-exposed-modules:
  - Proto.SimpleStorage.Messages
  - Proto.SimpleStorage.Messages_Fields

executables:
  simple-storage:
    source-dirs:
    - app
    main: Main.hs
    ghc-options:
    - -Werror
    - -Wall
    dependencies:
    - hs-abci-example

tests:
  hs-abci-example-test:
    main:                Spec.hs
    source-dirs:         test
    other-modules:
    - Tendermint.SDK.StoreExampleSpec
    ghc-options:
    - -Werror
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N


    dependencies:
      - generic-arbitrary
      - hs-abci-example
      - hs-abci-server
      - hspec
      - hspec-core
      - hspec-discover
      - binary
      - QuickCheck
      - quickcheck-instances
