name:                nameservice
version:             0.1.0.0
github:              "githubuser/nameservice"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"
synopsis:            "A synopsis"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/nameservice#readme>

extra-source-files:
- README.md

default-extensions:
  - DeriveGeneric
  - NamedFieldPuns
  - RecordWildCards
  - RankNTypes
  - TypeFamilies
  - FlexibleContexts
  - DataKinds
  - TypeApplications
  - OverloadedStrings
  - PolyKinds
  - GeneralizedNewtypeDeriving
  - ScopedTypeVariables
  - TupleSections
  - LambdaCase
  - GADTs
  - TypeOperators
  - FlexibleInstances
  - MultiParamTypeClasses
  - DefaultSignatures
  - FunctionalDependencies
  - TypeFamilyDependencies
  - DeriveFunctor
  - StandaloneDeriving
  - ConstraintKinds

library:
  source-dirs: nameservice/src
  dependencies:
    - aeson
    - aeson-casing
    - base >= 4.7 && < 5
    - bloodhound
    - errors
    - hs-abci-extra
    - hs-abci-server
    - hs-abci-sdk
    - hs-abci-types
    - http-client
    - katip
    - katip-elasticsearch
    - lens
    - polysemy
    - polysemy-plugin
    - proto3-suite
    - proto3-wire
    - servant
    - string-conversions
    - text
    - validation
  ghc-options:
  - -fplugin=Polysemy.Plugin
  - -Werror
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  exposed-modules:
  - Nameservice.Application
  - Nameservice.Config
  - Nameservice.Aeson
  - Nameservice.Server
  - Nameservice.Modules.Token
  - Nameservice.Modules.Token.Messages
  - Nameservice.Modules.Token.Types
  - Nameservice.Modules.Token.Keeper
  - Nameservice.Modules.Token.Query
  - Nameservice.Modules.Token.Router
  - Nameservice.Modules.Nameservice
  - Nameservice.Modules.Nameservice.Messages
  - Nameservice.Modules.Nameservice.Types
  - Nameservice.Modules.Nameservice.Keeper
  - Nameservice.Modules.Nameservice.Query
  - Nameservice.Modules.Nameservice.Router

executables:
  nameservice:
    main:                Main.hs
    source-dirs:         nameservice/app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hs-abci-sdk
    - katip
    - lens
    - nameservice

  gen-protos-exe:
    main:                Main.hs
    source-dirs:         nameservice/protogen
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson-casing
    - base
    - bytestring
    - hs-abci-sdk
    - nameservice
    - pretty
    - proto3-suite
    - proto3-wire

  interact:
    main:                Main.hs
    source-dirs:         nameservice/interact
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    dependencies:
    - async
    - base
    - data-default-class
    - faker
    - mtl
    - nameservice
    - hs-abci-sdk
    - hs-abci-test-utils
    - hs-tendermint-client
    - random-strings
    - servant
    - string-conversions
    - text

tests:
  tutorial:
    main:                README.lhs
    source-dirs:         nameservice/tutorial
    other-modules:
    - Tutorial.Nameservice.Application
    - Tutorial.Nameservice.Keeper
    - Tutorial.Nameservice.Message
    - Tutorial.Nameservice.Module
    - Tutorial.Nameservice.Query
    - Tutorial.Nameservice.Types
    ghc-options: -Wall -pgmL markdown-unlit
    dependencies:
    - aeson
    - base
    - hs-abci-sdk
    - hs-abci-server
    - lens
    - markdown-unlit
    - nameservice
    - polysemy
    - polysemy-plugin
    - proto3-suite
    - string-conversions
    - text
  nameservice-test:
    main:                Spec.hs
    source-dirs:         nameservice/test
    other-modules:
    - Nameservice.Test.E2ESpec
    - Nameservice.Test.EventOrphans
    ghc-options:
    - -Werror
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - data-default-class
    - hs-abci-sdk
    - hs-abci-test-utils
    - hs-tendermint-client
    - hspec
    - mtl
    - nameservice
    - servant
