name:                hs-abci-sdk
version:             0.1.0.0
github:              "f-o-a-m/hs-abci/hs-abci-sdk"
license:             Apache
author:              Martin Allen
maintainer:          "martin@foam.space"
copyright:           "2019 Martin Allen"

description:         Please see the README on GitHub at <https://github.com/f-o-a-m/hs-abci/hs-abci-sdk#readme>

default-extensions:
  - DeriveGeneric
  - NamedFieldPuns
  - RecordWildCards
  - RankNTypes
  - TypeFamilies
  - FlexibleContexts
  - DataKinds
  - TypeApplications
  - OverloadedStrings
  - PolyKinds
  - GeneralizedNewtypeDeriving
  - ScopedTypeVariables
  - TupleSections
  - LambdaCase
  - GADTs
  - TypeOperators
  - FlexibleInstances
  - MultiParamTypeClasses
  - DefaultSignatures
  - FunctionalDependencies
  - TypeFamilyDependencies
  - DeriveFunctor
  - StandaloneDeriving
  - ConstraintKinds
  - PackageImports


dependencies:
- aeson
- aeson-casing
- async
- avl-auth
- base >= 4.7 && < 5
- bech32
- binary
- bytestring
- containers
- conduit
- cryptonite
- data-default-class
- errors
- exceptions
- free
- hs-abci-types
- hs-abci-server
- http-types
- katip
- lens
- memory
- mtl
- polysemy
- polysemy-plugin
- profunctors
- servant
- stm
- string-conversions
- text
- uri-bytestring
- web3

library:
  source-dirs:
  - src
  ghc-options:
  - -fplugin=Polysemy.Plugin
  - -Werror
  - -Wall
  exposed-modules:
  - Tendermint.SDK.Store
  - Tendermint.SDK.Codec
  - Tendermint.SDK.StoreQueries
  - Tendermint.SDK.Subscription
  - Tendermint.SDK.AuthTreeStore
  - Tendermint.SDK.Router.Types
  - Tendermint.SDK.Router.Class
  - Tendermint.SDK.Router
  - Tendermint.SDK.BaseApp
  - Tendermint.SDK.Logger
  - Tendermint.SDK.Logger.Katip
  - Tendermint.SDK.Application
  - Tendermint.SDK.Auth
  - Tendermint.SDK.Aeson
  - Tendermint.SDK.Events
  - Tendermint.SDK.Errors
  
tests:
  hs-abci-sdk-test:
    main:                Spec.hs
    source-dirs:         test
    other-modules:
    - Tendermint.SDK.Test.AuthTreeStoreSpec
    # - Tendermint.SDK.Test.StoreExampleSpec
    - Tendermint.SDK.Test.ModuleSpec

    ghc-options:
    - -Werror
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    dependencies:
      - generic-arbitrary
      - hs-abci-server
      - hs-abci-sdk
      - hspec
      - hspec-core
      - hspec-discover
      - binary
      - QuickCheck
      - quickcheck-instances
