name:                hs-abci-sdk
version:             0.1.0.0
github:              "f-o-a-m/hs-abci/hs-abci-sdk"
license:             Apache
author:              Martin Allen
maintainer:          "martin@foam.space"
copyright:           "2019 Martin Allen"

description:         Please see the README on GitHub at <https://github.com/f-o-a-m/hs-abci/hs-abci-sdk#readme>

extra-source-files:
- protos/**/*.proto

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup

default-extensions:
  - DeriveGeneric
  - NamedFieldPuns
  - RecordWildCards
  - RankNTypes
  - TypeFamilies
  - FlexibleContexts
  - DataKinds
  - TypeApplications
  - OverloadedStrings
  - PolyKinds
  - GeneralizedNewtypeDeriving
  - ScopedTypeVariables
  - TupleSections
  - LambdaCase
  - GADTs
  - TypeOperators
  - FlexibleInstances
  - MultiParamTypeClasses
  - DefaultSignatures
  - FunctionalDependencies
  - TypeFamilyDependencies
  - DeriveFunctor
  - StandaloneDeriving
  - ConstraintKinds
  - PackageImports


dependencies:
- aeson
- aeson-casing
- async
- avl-auth
- base >= 4.7 && < 5
- bytestring
- cereal
- cereal-text
- containers
- cryptonite
- data-default-class
- errors
- exceptions
- hs-abci-types
- hs-abci-server
- hs-tendermint-client
- http-types
- katip
- lens
- memory
- mmorph
- mtl
- polysemy
- polysemy-plugin
- polysemy-zoo
- profunctors
- prometheus
- proto-lens
- proto-lens-runtime
- proto3-wire
- proto3-suite
- secp256k1-haskell
- servant
- stm
- string-conversions
- text
- time
- uri-bytestring
- validation

library:
  source-dirs:
  - src
  ghc-options:
  - -fplugin=Polysemy.Plugin
  - -Werror
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  exposed-modules:
  - Tendermint.SDK.Application
  - Tendermint.SDK.Application.App
  - Tendermint.SDK.Application.Module
  - Tendermint.SDK.Application.Handlers
  - Tendermint.SDK.BaseApp
  - Tendermint.SDK.BaseApp.BaseApp
  - Tendermint.SDK.BaseApp.CoreEff
  - Tendermint.SDK.BaseApp.Errors
  - Tendermint.SDK.BaseApp.Events
  - Tendermint.SDK.BaseApp.Gas
  - Tendermint.SDK.BaseApp.Logger
  - Tendermint.SDK.BaseApp.Logger.Katip
  - Tendermint.SDK.BaseApp.Metrics
  - Tendermint.SDK.BaseApp.Metrics.Prometheus
  - Tendermint.SDK.BaseApp.Query
  - Tendermint.SDK.BaseApp.Query.Class
  - Tendermint.SDK.BaseApp.Query.Client
  - Tendermint.SDK.BaseApp.Query.Delayed
  - Tendermint.SDK.BaseApp.Query.Router
  - Tendermint.SDK.BaseApp.Query.Store
  - Tendermint.SDK.BaseApp.Query.Types
  - Tendermint.SDK.BaseApp.Store
  - Tendermint.SDK.BaseApp.Store.AuthTreeStore
  - Tendermint.SDK.BaseApp.Store.RawStore
  - Tendermint.SDK.BaseApp.Store.Scope
  - Tendermint.SDK.Codec
  - Tendermint.SDK.Crypto
  - Tendermint.SDK.Modules.Auth
  - Tendermint.SDK.Types.Message
  - Tendermint.SDK.Types.Transaction
  - Tendermint.SDK.Types.Address
  - Tendermint.SDK.Types.TxResult

  generated-exposed-modules:
  - Proto.Types.Transaction
  - Proto.Types.Transaction_Fields

tests:
  hs-abci-sdk-test:
    main:                Spec.hs
    source-dirs:         test
    other-modules:
    - Tendermint.SDK.Test.AuthTreeStoreSpec
    - Tendermint.SDK.Test.CryptoSpec
    - Tendermint.SDK.Test.EventSpec
    - Tendermint.SDK.Test.GasSpec
    - Tendermint.SDK.Test.MetricsSpec

    ghc-options:
    - -fplugin=Polysemy.Plugin
    - -Werror
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    dependencies:
      - generic-arbitrary
      - hs-abci-server
      - hs-abci-sdk
      - hspec
      - hspec-core
      - hspec-discover
      - cereal
      - QuickCheck
      - quickcheck-instances
