name:                hs-abci-types
version:             0.1.0.0
github:              "f-o-a-m/hs-abci/hs-abci-types"
license:             Apache
author:              "Martin Allen"
maintainer:          "martin@foam.space"
copyright:           "2019 Martin Allen"

extra-source-files:
- protos/**/*.proto

description:         Please see the README on GitHub at <https://github.com/f-o-a-m/hs-abci/hs-abci-types#readme>

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup

default-extensions:
- NamedFieldPuns
- RecordWildCards
- FlexibleContexts
- DeriveGeneric
- TypeFamilies
- GADTs
- GeneralizedNewtypeDeriving
- DataKinds
- PolyKinds
- RankNTypes
- DataKinds
- ScopedTypeVariables
- FlexibleInstances
- OverloadedStrings
- MultiParamTypeClasses
- FunctionalDependencies


dependencies:
- base >= 4.7 && < 5
- bytestring
- lens
- proto-lens

library:
  source-dirs: src
  ghc-options:
  - -Werror
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  dependencies:
    - aeson
    - aeson-casing
    - base16-bytestring
    - data-default-class
    - memory
    - proto-lens-runtime
    - string-conversions
    - text
    - template-haskell
    - time
  exposed-modules:
  - Data.ByteArray.HexString
  - Data.ByteArray.Base64String
  - Network.ABCI.Types.Messages.Request
  - Network.ABCI.Types.Messages.Response
  - Network.ABCI.Types.Messages.FieldTypes
  generated-exposed-modules:
  - Proto.Types
  - Proto.Types_Fields
  - Proto.Vendored.Gogo.Protobuf.Gogoproto.Gogo
  - Proto.Vendored.Gogo.Protobuf.Gogoproto.Gogo_Fields
  - Proto.Vendored.Google.Protobuf.Timestamp
  - Proto.Vendored.Google.Protobuf.Timestamp_Fields
  - Proto.Vendored.Tendermint.Tendermint.Crypto.Merkle.Merkle
  - Proto.Vendored.Tendermint.Tendermint.Crypto.Merkle.Merkle_Fields
  - Proto.Vendored.Tendermint.Tendermint.Libs.Common.Types
  - Proto.Vendored.Tendermint.Tendermint.Libs.Common.Types_Fields

tests:
  hs-abci-types-test:
    main:                Spec.hs
    source-dirs:         test
    other-modules:
    - Network.ABCI.Test.Types.Messages.Instances
    - Network.ABCI.Test.Types.MessagesSpec
    - Test.Data.ByteArray.HexStringSpec
    ghc-options:
    - -Werror
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N


    dependencies:
      - generic-arbitrary
      - hs-abci-types
      - hspec
      - hspec-core
      - hspec-discover
      - binary
      - lens-labels
      - proto-lens-arbitrary
      - QuickCheck
      - quickcheck-instances
