language: haskell
ghc:
  - "8.6.1"
cabal: "2.4"
sudo: required
# Cache .stack for build_times--
addons:
  apt:
    sources:
    - sourceline: 'ppa:tah83/secp256k1'
    packages:
    - libsecp256k1-dev

cache:
  directories:
  - $HOME/.stack
before_install:
# Download and unpack the stack executable
- git clone https://github.com/bitcoin-core/secp256k1.git && cd secp256k1 && ./autogen.sh && ./configure --enable-module-recovery && make && ./tests && sudo make install && cd ..
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
# From https://github.com/google/proto-lens/blob/5ab25dfeb51f700204db4aa8a9e7fbc5a74ed1e9/.travis.yml#L41-L44
- curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-x86_64.zip > protoc-release.zip
- unzip -p protoc-release.zip bin/protoc > $HOME/.local/bin/protoc
- chmod a+x $HOME/.local/bin/protoc
- rm protoc-release.zip
install:
- travis_wait 120 stack --skip-ghc-check setup
- travis_wait 120 stack --skip-ghc-check install hlint-2.1.26 stylish-haskell-0.9.4.3
script:
- make hlint

# When branch is `master` we run `haskell-stylish` and fail if git working directory becomes dirty
- if [ "$TRAVIS_BRANCH" == "master" ]; then make stylish && git diff-index --quiet HEAD; fi

- make test-libraries
# commenting for now as this build is broken with the addition of secp256k1
# and will uncomment and fix  when we are using again.
#- curl https://nixos.org/nix/install | sh
#- . $HOME/.nix-profile/etc/profile.d/nix.sh
#- stack --nix test hs-abci-types hs-abci-server hs-abci-sdk
