# https://www.stackage.org/lts-13.27
resolver: lts-14.11

nix:
  #enabled: bool # defaults to true on nixos, false everywhere else
  shell-file: shell-stack.nix

packages:
- ./hs-abci-types
- ./hs-tendermint-client
- ./hs-abci-server
- ./hs-abci-extra
- ./hs-abci-sdk
- ./hs-abci-examples/simple-storage
- ./hs-abci-examples/nameservice
- ./hs-iavl-client

extra-deps:
  - proto-lens-runtime-0.5.0.0
  - proto-lens-setup-0.4.0.2
  - lens-labels-0.3.0.1
  - proto-lens-0.5.0.0
  - proto-lens-protoc-0.5.0.0
  - git: https://github.com/oscoin/avl-auth
    commit: dfc468845a82cdd7d759943b20853999bc026505
  - git: https://github.com/awakesecurity/proto3-suite
    commit: 3f6dd6f612cf2eba3c05798926ff924b0d5ab4fa
  - git: https://github.com/awakesecurity/proto3-wire
    commit: 23015cf6363d1962fde6bdff0de111f7ec59ab75
  - polysemy-1.2.3.0
  - polysemy-zoo-0.6.0.0
  - http2-client-0.9.0.0
  - http2-grpc-types-0.4.0.0
  - git: https://github.com/lucasdicioccio/http2-client-grpc
    commit: 6a1aacfc18e312ef57552133f13dd1024c178706

explicit-setup-deps:
  hs-abci-server: true
