# https://www.stackage.org/lts-13.27
resolver: lts-14.11

packages:
- ./hs-abci-types
- ./hs-tendermint-client
- ./hs-abci-server
- ./hs-abci-extra
- ./hs-abci-examples/simple-storage
- ./hs-abci-sdk

extra-deps:
  - proto-lens-runtime-0.5.0.0
  - proto-lens-setup-0.4.0.2
  - lens-labels-0.3.0.1
  - proto-lens-0.5.0.0
  - proto-lens-protoc-0.5.0.0
  - git: https://github.com/oscoin/avl-auth
    commit: dfc468845a82cdd7d759943b20853999bc026505
  - stylish-haskell-0.9.4.3@sha256:98f60e087ee3e661220cd3e1cf77677d4cecd3b90d110f7ce6f36babb5c2f895,4953
  - hlint-2.1.26@sha256:e0489fd31bc4a531aaf27d7e6b9814b50863b2a78c10e1d77e7b652b00933c9b,3231

explicit-setup-deps:
  hs-abci-server: true
