# https://www.stackage.org/lts-13.27
resolver: lts-13.27

packages:
- ./hs-abci-server
- ./hs-abci-example
- ./hs-abci-extra
- ./hs-abci-types
- ./hs-tendermint-client

extra-deps:
  - proto-lens-runtime-0.5.0.0
  - proto-lens-setup-0.4.0.2
  - lens-labels-0.3.0.1
  - proto-lens-0.5.0.0
  - proto-lens-protoc-0.5.0.0
  - git: https://github.com/oscoin/avl-auth
    commit: dfc468845a82cdd7d759943b20853999bc026505

explicit-setup-deps:
  hs-abci-server: true
