version: '3.7'
services:
  tendermint-init:
    image: tendermint/tendermint:v0.32.8
    command: init
    volumes:
        - /tmp:/tendermint
  tendermint:
    depends_on:
      - tendermint-init
      - simple_storage
    image: tendermint/tendermint:v0.32.8
    command: node --rpc.laddr=tcp://0.0.0.0:25567 --proxy_app=tcp://simple_storage:26658
    volumes:
      - /tmp:/tendermint
    restart: always
    ports:
      - "26656-26657:26656-26657"
  simple_storage:
    build:
      context: ../../.
      dockerfile: hs-abci-examples/simple-storage/Dockerfile
    restart: always
    expose:
      - "26658"
