name:                simple-storage
version:             0.1.0.0
github:              "f-o-a-m/hs-abci/hs-abci-examples/simple-storage"
license:             Apache
author:              Martin Allen
maintainer:          "martin@foam.space"
copyright:           "2019 Martin Allen"

extra-source-files:
- protos/**/*.proto

description:         Please see the README on GitHub at <https://github.com/f-o-a-m/hs-abci/hs-abci-examples/simple-storage#readme>

default-extensions:
  - DeriveGeneric
  - NamedFieldPuns
  - RecordWildCards
  - RankNTypes
  - TypeFamilies
  - FlexibleContexts
  - DataKinds
  - TypeApplications
  - OverloadedStrings
  - PolyKinds
  - GeneralizedNewtypeDeriving
  - ScopedTypeVariables
  - TupleSections
  - LambdaCase
  - GADTs
  - TypeOperators
  - FlexibleInstances
  - MultiParamTypeClasses
  - DefaultSignatures
  - FunctionalDependencies
  - TypeFamilyDependencies
  - DeriveFunctor
  - StandaloneDeriving
  - ConstraintKinds


dependencies:
- aeson
- async
- avl-auth
- base >= 4.7 && < 5
- bytestring
- cereal
- cereal-text
- containers
- conduit
- cryptonite
- data-default-class
- errors
- exceptions
- free
- hs-abci-extra
- hs-abci-server
- hs-abci-types
- hs-abci-extra
- hs-abci-sdk
- http-types
- kan-extensions
- katip
- lens
- memory
- mtl
- polysemy
- polysemy-plugin
- proto-lens
- proto-lens-runtime
- servant
- stm
- string-conversions
- text
- uri-bytestring

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup

library:
  source-dirs:
  - src
  ghc-options:
  - -fplugin=Polysemy.Plugin
  - -Werror
  - -Wall
  exposed-modules:
  - SimpleStorage.Server
  - SimpleStorage.Application
  - SimpleStorage.Handlers
  - SimpleStorage.Modules.SimpleStorage
  - SimpleStorage.Types

  generated-exposed-modules:
  - Proto.SimpleStorage.Messages
  - Proto.SimpleStorage.Messages_Fields

executables:
  simple-storage:
    source-dirs:
    - app
    main: Main.hs
    ghc-options:
    - -Werror
    - -Wall
    dependencies:
    - simple-storage

tests:
  simple-storage-test:
    main:                Spec.hs
    source-dirs:         test
    other-modules:
    - SimpleStorage.Test.E2ESpec
    - SimpleStorage.Test.HandlersSpec
    ghc-options:
    - -Werror
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - aeson
      - aeson-pretty
      - simple-storage
      - hs-abci-types
      - hs-tendermint-client
      - hspec
      - QuickCheck
