name:                hs-abci-server
version:             0.1.0.0
github:              "f-o-a-m/kepler/hs-abci-server"
license:             Apache
author:              "Martin Allen"
maintainer:          "martin@foam.space"
copyright:           "2020 Martin Allen"

description:         Please see the README on GitHub at <https://github.com/f-o-a-m/kepler/hs-abci-server#readme>

default-extensions:
- NamedFieldPuns
- RecordWildCards
- FlexibleContexts
- DeriveGeneric
- TypeFamilies
- GADTs
- DataKinds
- PolyKinds
- RankNTypes
- DataKinds
- ScopedTypeVariables
- FlexibleInstances
- OverloadedStrings
- MultiParamTypeClasses
- FunctionalDependencies
- TypeApplications

library:
  source-dirs: src
  ghc-options:
  - -Werror
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  dependencies:
    - aeson
    - base >= 4.7 && < 5
    - bytestring
    - base16-bytestring
    - conduit
    - conduit-extra
    - cryptonite
    - data-default-class
    - hs-abci-types
    - lens
    - memory
    - proto-lens
    - string-conversions
    - text

  exposed-modules:
  - Network.ABCI.Server
  - Network.ABCI.Server.App
  - Network.ABCI.Server.App.DecodeError

tests:
  hs-abci-server-test:
    main:                Spec.hs
    source-dirs:         test
    other-modules:
    - Network.ABCI.Test.Server.AppSpec
    ghc-options:
    - -Werror
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N


    dependencies:
      - base >= 4.7 && < 5
      - bytestring
      - hs-abci-server
      - hspec
      - hspec-core
      - hspec-discover
      - binary
      - QuickCheck
