name:                hs-abci-server
version:             0.1.0.0
github:              "f-o-a-m/hs-abci/hs-abci-server"
license:             Apache
author:              "Martin Allen"
maintainer:          "martin@foam.space"
copyright:           "2019 Martin Allen"

extra-source-files:
- protos/**/*.proto

description:         Please see the README on GitHub at <https://github.com/f-o-a-m/hs-abci/hs-abci-server#readme>

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup

default-extensions:
- NamedFieldPuns
- RecordWildCards
- FlexibleContexts
- DeriveGeneric
- TypeFamilies
- GADTs
- DataKinds
- PolyKinds
- RankNTypes
- DataKinds
- ScopedTypeVariables
- FlexibleInstances
- OverloadedStrings


dependencies:
- base >= 4.7 && < 5
- bytestring
- base16-bytestring
- data-default-class
- lens
- proto-lens
- proto-lens-runtime
- text
- time
- conduit
- conduit-extra
- string-conversions

library:
  source-dirs: src
  ghc-options:
  - -Werror
  - -Wall
  exposed-modules:
  - Network.ABCI
  - Network.ABCI.Types.App
  - Network.ABCI.Types.DecodeError
  - Network.ABCI.Types.Messages.Request
  - Network.ABCI.Types.Messages.Response
  - Network.ABCI.Types.Messages.FieldTypes
  - Network.ABCI.Types.Messages.Types
  generated-exposed-modules:
  - Proto.Types
  - Proto.Types_Fields
  - Proto.Vendored.Gogo.Protobuf.Gogoproto.Gogo
  - Proto.Vendored.Gogo.Protobuf.Gogoproto.Gogo_Fields
  - Proto.Vendored.Google.Protobuf.Timestamp
  - Proto.Vendored.Google.Protobuf.Timestamp_Fields
  - Proto.Vendored.Tendermint.Tendermint.Crypto.Merkle.Merkle
  - Proto.Vendored.Tendermint.Tendermint.Crypto.Merkle.Merkle_Fields
  - Proto.Vendored.Tendermint.Tendermint.Libs.Common.Types
  - Proto.Vendored.Tendermint.Tendermint.Libs.Common.Types_Fields

tests:
  hs-abci-server-test:
    main:                Spec.hs
    source-dirs:         test
    other-modules:
    - Network.ABCI.Test.Types.Messages.Instances
    - Network.ABCI.Test.Types.MessagesSpec
    - Network.ABCI.Test.Types.AppSpec
    ghc-options:
    - -Werror
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N


    dependencies:
      - generic-arbitrary
      - hs-abci-server
      - hspec
      - hspec-core
      - hspec-discover
      - binary
      - lens-labels
      - proto-lens-arbitrary
      - QuickCheck
      - quickcheck-instances
