name:                hs-abci-extra
version:             0.1.0.0
github:              "https://github.com/f-o-a-m/kepler/hs-abci-server"
license:             Apache
author:              "Martin Allen"
maintainer:          "martin@foam.space"
copyright:           "2020 Martin Allen"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/f-o-a-m/kepler/blob/master/hs-abci-server/README.md>

dependencies:
- base >= 4.7 && < 5

default-extensions:
- NamedFieldPuns
- RecordWildCards
- FlexibleContexts
- DeriveGeneric
- TypeFamilies
- GADTs
- DataKinds
- PolyKinds
- RankNTypes
- DataKinds
- ScopedTypeVariables
- FlexibleInstances
- OverloadedStrings

library:
  source-dirs: src
  dependencies:
    - aeson
    - containers
    - katip
    - hs-abci-server
    - hs-abci-types
    - prometheus
    - string-conversions
    - time
    - transformers
  ghc-options:
  - -Werror
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
