version: '3.7'
services:
  tendermint-init:
    image: tendermint/tendermint:v0.32.8
    command: init
    volumes:
        - tendermint-storage:/tendermint
  tendermint:
    depends_on:
      - tendermint-init
      - nameservice
    image: tendermint/tendermint:v0.32.8
    command: node --rpc.laddr=tcp://0.0.0.0:26657 --proxy_app=tcp://nameservice:26658
    volumes:
      - tendermint-storage:/tendermint
    restart: always
    ports:
      - "26656-26657:26656-26657"
  nameservice:
    entrypoint: /usr/local/bin/nameservice
    build:
      context: ../../.
      dockerfile: Dockerfile
    image: hs-abci:test
    environment:
     - ES_HOST=elk
     - ES_PORT=9200
     - STATS_PORT=5555
    restart: always
    depends_on:
      - elk
      - datadog
    expose:
      - "26658"
      - "5555"
  datadog:
    image: datadog/agent:latest
    environment:
     - DD_API_KEY=${DD_API_KEY}
    volumes:
     - conf.d/openmetrics.d:/etc/datadog-agent/conf.d/openmetrics.d
  elk:
    image: sebp/elk:683
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    expose:
      - "9200"
      - "5601"
volumes:
  tendermint-storage:
