name:                nameservice
version:             0.1.0.0
github:              "githubuser/nameservice"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/nameservice#readme>

extra-source-files:
- README.md

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup

default-extensions:
  - DeriveGeneric
  - NamedFieldPuns
  - RecordWildCards
  - RankNTypes
  - TypeFamilies
  - FlexibleContexts
  - DataKinds
  - TypeApplications
  - OverloadedStrings
  - PolyKinds
  - GeneralizedNewtypeDeriving
  - ScopedTypeVariables
  - TupleSections
  - LambdaCase
  - GADTs
  - TypeOperators
  - FlexibleInstances
  - MultiParamTypeClasses
  - DefaultSignatures
  - FunctionalDependencies
  - TypeFamilyDependencies
  - DeriveFunctor
  - StandaloneDeriving
  - ConstraintKinds

dependencies:
- aeson
- aeson-casing
- base >= 4.7 && < 5
- binary
- bytestring
- exceptions
- hs-abci-extra
- hs-abci-sdk
- hs-abci-server
- hs-abci-types
- lens
- polysemy
- pretty
- proto-lens
- proto-lens-runtime
- proto3-suite
- proto3-wire
- katip
- servant
- string-conversions
- text

library:
  source-dirs: src
  exposed-modules:
  - Nameservice.Application
  - Nameservice.Server
  - Nameservice.Modules.Nameservice.Messages
  - Nameservice.Modules.Nameservice.Types
  - Nameservice.Modules.Nameservice.Keeper
  - Nameservice.Modules.Nameservice.Query
  - Nameservice.Modules.Nameservice.Router

  generated-exposed-modules:
  - Proto.Nameservice.Messages
  - Proto.Nameservice.Messages_Fields
  - Proto.Nameservice.Whois
  - Proto.Nameservice.Whois_Fields

executables:
  nameservice-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nameservice

tests:
  nameservice-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nameservice
    - hspec
