name:                nameservice
version:             0.1.0.0
github:              "githubuser/nameservice"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/nameservice#readme>

extra-source-files:
- README.md

default-extensions:
  - DeriveGeneric
  - NamedFieldPuns
  - RecordWildCards
  - RankNTypes
  - TypeFamilies
  - FlexibleContexts
  - DataKinds
  - TypeApplications
  - OverloadedStrings
  - PolyKinds
  - GeneralizedNewtypeDeriving
  - ScopedTypeVariables
  - TupleSections
  - LambdaCase
  - GADTs
  - TypeOperators
  - FlexibleInstances
  - MultiParamTypeClasses
  - DefaultSignatures
  - FunctionalDependencies
  - TypeFamilyDependencies
  - DeriveFunctor
  - StandaloneDeriving
  - ConstraintKinds

dependencies:
- aeson
- aeson-casing
- base >= 4.7 && < 5
- bytestring
- cereal
- data-default-class
- errors
- exceptions
- either
- hs-abci-extra
- hs-abci-sdk
- hs-abci-server
- hs-abci-types
- lens
- polysemy
- pretty
- proto-lens
- proto-lens-runtime
- proto3-suite
- proto3-wire
- katip
- servant
- string-conversions
- text
- validation

library:
  source-dirs: src
  exposed-modules:
  - Nameservice.Application
  - Nameservice.Server
  - Nameservice.Handlers
  - Nameservice.Modules.Token
  - Nameservice.Modules.Nameservice.Messages
  - Nameservice.Modules.Nameservice.Types
  - Nameservice.Modules.Nameservice.Keeper
  - Nameservice.Modules.Nameservice.Query
  - Nameservice.Modules.Nameservice.Router

executables:
  nameservice-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nameservice

  gen-protos-exe:
    main:                Main.hs
    source-dirs:         protogen
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nameservice

tests:
  nameservice-test:
    main:                Spec.hs
    source-dirs:         test
    other-modules:
    - Nameservice.Test.E2ESpec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nameservice
    - aeson-pretty
    - hspec
    - hs-tendermint-client
