version: '3.7'
services:
  tendermint-init:
    image: tendermint/tendermint:v0.32.8
    command: init
    volumes:
        - tendermint-storage:/tendermint
  tendermint:
    depends_on:
      - tendermint-init
      - kvstore
    image: tendermint/tendermint:v0.32.8
    command: node --rpc.laddr tcp://0.0.0.0:26657 --proxy_app=tcp://kvstore:26658
    volumes:
      - tendermint-storage:/tendermint
    restart: always
    ports:
      - "26656-26657:26656-26657"
  kvstore:
    build:
      context: ./
      dockerfile: Dockerfile.abci-cli
      args:
        TENDERMINT_VERSION: v0.32.8
    restart: always
    command: kvstore
    expose:
      - "26658"
volumes:
  tendermint-storage:
