name:                hs-tendermint-client
version:             0.1.0.0
github:              "f-o-a-m/hs-abci/hs-tendermint-client"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/f-o-a-m/hs-abci/hs-tendermint-client#readme>

default-extensions:
- NamedFieldPuns
- RecordWildCards
- FlexibleContexts
- DeriveGeneric
- TypeFamilies
- TypeApplications
- GADTs
- DataKinds
- PolyKinds
- RankNTypes
- DataKinds
- ScopedTypeVariables
- FlexibleInstances
- OverloadedStrings
- GeneralizedNewtypeDeriving

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- exceptions
- data-default-class

library:
  source-dirs: src
  dependencies:
    - aeson-casing
    - hs-abci-types
    - http-client
    - http-conduit
    - mtl
    - random
    - text
  ghc-options:
  - -Werror
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  exposed-modules:
  - Network.Tendermint.Client
  - Network.Tendermint.Client.Internal.RPCClient

tests:
  hs-tendermint-client-kv:
    main:                Spec.hs
    source-dirs:         kv-test
    other-modules:
    - KVStore.Test.KVSpec
    ghc-options:
    - -Werror
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - aeson-pretty
      - hs-abci-types
      - hs-tendermint-client
      - hspec
      - lens
      - string-conversions
