name:                hs-tendermint-client
version:             0.1.0.0
github:              "f-o-a-m/hs-abci/hs-tendermint-client"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/f-o-a-m/hs-abci/hs-tendermint-client#readme>

default-extensions:
- NamedFieldPuns
- RecordWildCards
- FlexibleContexts
- DeriveGeneric
- TypeFamilies
- GADTs
- DataKinds
- PolyKinds
- RankNTypes
- DataKinds
- ScopedTypeVariables
- FlexibleInstances
- OverloadedStrings


dependencies:
- base >= 4.7 && < 5
- bytestring
- base16-bytestring
- text
- time
- exceptions
- mtl
- http-conduit
- http-client
- random
- aeson
- aeson-casing
- memory
- hs-abci-types

library:
  source-dirs: src
  ghc-options:
  - -Werror
  - -Wall
  exposed-modules:
  - Network.Tendermint.Client
